---

- name: Ensure tmp directory exists.
  ansible.builtin.file:
    path: "{{ tmp_backup_dir }}"
    state: directory

- name: Ensure git repo directory exists.
  ansible.builtin.file:
    path: "{{ git_repo_dir }}"
    state: directory
