---

- name: Pull git repository.
  ansible.builtin.git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_dir }}"
    version: "{{ git_branch }}"
    force: true
    update: true
    accept_hostkey: true
